modLoader="javafml"
loaderVersion="[47,)"

license="${mod_license}"


#issueTrackerURL="https://github.com/MinecraftForge/MinecraftForge/issues"
#showAsResourcePack=false
#clientSideOnly=false

[[mods]]
    modId="arrowdmglimit"
    version="1.0.0"
    displayName="Arrow damage Limit"
    #updateJSONURL="https://raw.githubusercontent.com/Lothrazar/ForgeTemplate/trunk/1.20/update.json" #optional
    #displayURL="https://www.curseforge.com/minecraft/mc-mods/_curseslug_"
    #logoFile=""
    credits="Thanks to forge fml mcp Mojang"
    authors="oscarbaltasar"
    description='''
    arrowdmglimit by oscarbaltasar
    '''
    #displayTest="MATCH_VERSION"

[[dependencies.arrowdmglimit]]
    modId="forge" 
    mandatory=true 
    versionRange="[47,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.arrowdmglimit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="SERVER"
	
	